services:
    ktq.twig.extension:
        class: KTQ\Bundle\eZExceedBundle\Twig\eZExceedTwigExtension
        arguments: [ @ezpublish.api.repository, @ezpublish_legacy.config.resolver, @templating, @ktq.twig.pencil.model ]
        tags:
            - { name: twig.extension }

    ktq.twig.pencil.model:
        class: KTQ\Bundle\eZExceedBundle\Model\Pencil
        arguments: [ @service_container ]
        lazy: true

    ezpublish.fieldType.ezpage.pageService:
        class: %ezpublish.fieldType.ezpage.pageService.class%
        factory_service: ezpublish.fieldType.ezpage.pageService.factory
        factory_method: buildService
        arguments:
            - %ezpublish.fieldType.ezpage.pageService.class%
            - @ezpublish.config.resolver
            - @ezpublish.fieldType.ezpage.storage_gateway
            - @ezpublish.api.service.content
        lazy: true
        calls:
            -
                [ setContainer, [@service_container] ]
